// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
	"player-demo": {
		files: ["../lib/registry/examples/player-demo.svelte"],
	},
	"player-stacked-layout-demo": {
		files: ["../lib/registry/examples/player-stacked-layout-demo.svelte"],
	},
	"player-with-queue-demo": {
		files: ["../lib/registry/examples/player-with-queue-demo.svelte"],
	},
};
