// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
	"fader-custom-thumb-marks-demo": {
		files: ["../lib/registry/examples/fader-custom-thumb-marks-demo.svelte"],
	},
	"fader-demo": {
		files: ["../lib/registry/examples/fader-demo.svelte"],
	},
	"fader-horizontal-demo": {
		files: ["../lib/registry/examples/fader-horizontal-demo.svelte"],
	},
	"fader-multiple-control-demo": {
		files: ["../lib/registry/examples/fader-multiple-control-demo.svelte"],
	},
	"fader-no-thumb-marks-demo": {
		files: ["../lib/registry/examples/fader-no-thumb-marks-demo.svelte"],
	},
	"fader-volume-control-demo": {
		files: ["../lib/registry/examples/fader-volume-control-demo.svelte"],
	},
	"knob-demo": {
		files: ["../lib/registry/examples/knob-demo.svelte"],
	},
	"knob-filter-control-demo": {
		files: ["../lib/registry/examples/knob-filter-control-demo.svelte"],
	},
	"knob-multiple-control-demo": {
		files: ["../lib/registry/examples/knob-multiple-control-demo.svelte"],
	},
	"knob-size-variants-demo": {
		files: ["../lib/registry/examples/knob-size-variants-demo.svelte"],
	},
	"playback-speed-demo": {
		files: ["../lib/registry/examples/playback-speed-demo.svelte"],
	},
	"player-demo": {
		files: ["../lib/registry/examples/player-demo.svelte"],
	},
	"player-stacked-layout-demo": {
		files: ["../lib/registry/examples/player-stacked-layout-demo.svelte"],
	},
	"player-with-queue-demo": {
		files: ["../lib/registry/examples/player-with-queue-demo.svelte"],
	},
	"queue-all-controls-demo": {
		files: ["../lib/registry/examples/queue-all-controls-demo.svelte"],
	},
	"queue-preferences-demo": {
		files: ["../lib/registry/examples/queue-preferences-demo.svelte"],
	},
	"queue-shuffle-repeat-demo": {
		files: ["../lib/registry/examples/queue-shuffle-repeat-demo.svelte"],
	},
	"queue-simple-demo": {
		files: ["../lib/registry/examples/queue-simple-demo.svelte"],
	},
	"slider-demo": {
		files: ["../lib/registry/examples/slider-demo.svelte"],
	},
	"sortable-list-demo": {
		files: ["../lib/registry/examples/sortable-list-demo.svelte"],
	},
	"track-demo": {
		files: ["../lib/registry/examples/track-demo.svelte"],
	},
	"track-list-demo": {
		files: ["../lib/registry/examples/track-list-demo.svelte"],
	},
	"track-list-grid-demo": {
		files: ["../lib/registry/examples/track-list-grid-demo.svelte"],
	},
	"track-sortable-list-demo": {
		files: ["../lib/registry/examples/track-sortable-list-demo.svelte"],
	},
	"track-sortable-list-grid-demo": {
		files: ["../lib/registry/examples/track-sortable-list-grid-demo.svelte"],
	},
	"xypad-demo": {
		files: ["../lib/registry/examples/xypad-demo.svelte"],
	},
	"xypad-filter-control-demo": {
		files: ["../lib/registry/examples/xypad-filter-control-demo.svelte"],
	},
	"xypad-format-value-demo": {
		files: ["../lib/registry/examples/xypad-format-value-demo.svelte"],
	},
	"xypad-hide-value-demo": {
		files: ["../lib/registry/examples/xypad-hide-value-demo.svelte"],
	},
	"xypad-synthesizer-control-demo": {
		files: ["../lib/registry/examples/xypad-synthesizer-control-demo.svelte"],
	},
};
