// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type overview = Collections['overview']['schema']['_output']
export declare const overview: overview[]

export type components = Collections['components']['schema']['_output']
export declare const components: components[]

export type ui = Collections['ui']['schema']['_output']
export declare const ui: ui[]

export type libs = Collections['libs']['schema']['_output']
export declare const libs: libs[]
