import fs from "node:fs";
import path from "node:path";

function buildRegistry() {
	const registryDir = path.resolve("src", "lib", "components", "ui", "audio", "examples");
	const outputDir = path.resolve("src", "__registry__");
	const outputFile = path.join(outputDir, "index.js");

	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	let indexContent = `// This file is autogenerated by scripts/build-registry.ts\n// Do not edit this file directly.\nexport const Index = {\n`;

	if (fs.existsSync(registryDir)) {
		const files = fs.readdirSync(registryDir);

		for (const file of files) {
			if (file.endsWith(".svelte") || file.endsWith(".ts")) {
				const name = file.replace(/\.(svelte|ts)$/, "");

				const relativePath = path.posix.join(
					"../lib/components/ui",
					"audio",
					"examples",
					file
				);
				indexContent += `\t"${name}": {\n\t\tfiles: ["${relativePath}"],\n\t},\n`;
			}
		}
	}

	indexContent += `};\n`;

	fs.writeFileSync(outputFile, indexContent, "utf8");
	console.log("Registry index generated successfully at", outputFile);
}

buildRegistry();
